apiVersion: v1
kind: Service
metadata:
  namespace: np-services-k8s
  name: msx-auth
spec:
  type: LoadBalancer
  ports:
    - port: 3010
      targetPort: 3010
  selector:
    app: msx-auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: np-services-k8s
  name: msx-auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msx-auth
  template:
    metadata:
      labels:
        app: msx-auth
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: msx-auth
          image: knguyen2507/msx-auth:latest
          ports:
            - containerPort: 3010
          envFrom:
            - secretRef:
                name: np-services-kubernetes-secret
          env:
            - name: PORT
              value: '3010'
